server:
  port: 8081

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alin-2924/Microservicios-Veterinaria
          default-label: main
          search-paths: .