spring.application.name=Clientes

server.port=8004

spring.datasource.url: jdbc:h2:mem:midb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: UNECOM
spring.datasource.password: AI243sj
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true

